### PR TITLE
Use FQFN

### PR DESCRIPTION
**Pull request by snapshotpl**
This repository use many internal php function. For example in my application when I use `Zend\Crypt\BlockCipher` class `hash_hmac` function is call 10k times  and take ~23ms! This change should have perfomance visible impact

### CODE REVIEW

**Review by michalbundyra — COMMENTED** [review]
The same we have done in https://github.com/zendframework/zend-servicemanager/pull/198 but a bit different way - we import all functions on top. I would prefer that way, because we just add new lines and we don't need to modify anything else. Please note I have wrote sniff in zend-coding-standard which do it automatically ;-)

**Comment by snapshotpl** [comment]
@webimpress Is it an "official" way to do that in zf?

**Comment by michalbundyra** [comment]
Hm... I just only know that we have done this way in zend-code:
https://github.com/zendframework/zend-code/pull/121
and zend-service as I've mentioned before. Both PR were merged and released. I would then go this way and import these functions. As I mentioned you can use my sniff, which will do all for you automatically 😄

**Comment by weierophinney** [comment]
Thanks, @snapshotpl!

**Pull request merged**
