### PR TITLE
Create BcryptShaBase64.php

### PR DESCRIPTION
**Pull request by paragonie-scott**
This is compatible with [`ParagonIE\PasswordLock`](https://github.com/paragonie/password_lock) before the authenticated encryption is performed.

### CODE REVIEW

**Comment by ezimuel** [comment]
@paragonie-scott we already have [Zend\Crypt\Hash\BcryptSha](https://github.com/zendframework/zend-crypt/blob/master/src/Password/BcryptSha.php). Regarding the difference with your proposal we don't use binary output for hash and we don't encode it in base64, but you can easily obtain this result using the functions `hex2bin()`, `bin2hex()` and `base64_encode/decode()`, for instance:

``` php
use Zend\Crypt\Hash\BcryptSha;

$bcryptSha = new BcryptSha();
$password = 'password to hash';
$hash = base64_encode(hex2bin($bcryptSha->create('password to hash')));
if ($bcryptSha->verify($password, bin2hex(base64_decode($hash)))) {
    echo "The password is correct!";
}
```

**Comment by paragonie-scott** [comment]
The order of operations is wrong in your sample code.

You did:

```
base64_encode(
    bcrypt(
        sha2_hex(
            $str
        )
    )
)
```

I proposed

```
bcrypt(
    base64_encode(
        sha2_raw(
            $str
        )
    )
)
```

But if this is not desired, I will not send another PR.

**Comment by ezimuel** [comment]
@paragonie-scott you right, I confused the order looking at the implementation. Why did you apply a bcrypt on a base64 string? I see a potential problem here regarding the entropy of the input space. Base64 will contain 3/4th of the entropy of a fully binary value. Don't you think this can be a problem?

**Comment by paragonie-scott** [comment]
No, it doesn't quite work that way.

When you encode a binary string in base64, you don't reduce the **total** entropy of the string, you remove the entropy _of each character_. A base64 string is 4/3 (rounded up) the length of the input string. The total entropy is preserved.

See [this post by ircmaxell](http://blog.ircmaxell.com/2015/03/security-issue-combining-bcrypt-with.html) for why I wrote the base64 approach in my PasswordLock implementation. I submitted this PR just so that, in case someone got concerned about vendor lock-in, they could easily decrypt their encrypted PasswordLock hashes and use `Zend\Crypt` instead.

**Comment by ezimuel** [comment]
@paragonie-scott ok you right about entropy, it doesn't loose the entire space only for characters. 
But the question about base64 usage is still valid, why you didn't use just hash with hex output (default)? I'm just curios about that and thanks for your explanation.

**Comment by paragonie-scott** [comment]
Because at the time I was considering using SHA512 and `64 * 4/3` means less entropy gets truncated after 72 characters than `64 * 2` (with hexadecimal). I'm not sure when/why I went with sha256.

**Comment by ezimuel** [comment]
@paragonie-scott ok I see. I'm sorry to have closed this PR at the beginning but I was sure about the example code that I provided. Anyway, I don't think this class will be helpful for the majority of ZF users. Thanks anyway!

**Pull request closed without merging**
