### PR TITLE
Fixed typo in test method name: `testEncryptWithoutSalt`

### PR DESCRIPTION
**Pull request by mountain-nerd**

### CODE REVIEW

**Comment by Ocramius** [comment]
This cannot be changed anymore, as it would be a BC break.

Sorry, closing as `inapplicable`.

**Comment by froschdesign** [comment]
@Ocramius 
This is an unit test and not a part of the public API!

**Comment by Ocramius** [comment]
Urgh, I really need to read namespaces better -.-

Sorry @AshishThakur, re-opening.

**Comment by Ocramius** [comment]
Manually merged to `develop` via zendframework/zend-crypt@40b29b5f4c7a6a8fc0b36d9d07351f86f01036a4

**Pull request closed without merging**
